[font]
size = 11

[font.normal]
family = "FiraCode Nerd Font"

[font.offset]
x = 0
y = 0

[window]
decorations = "full"
dynamic_title = false
opacity = 0.96

[window.dimensions]
columns = 140
lines = 40

[window.padding]
x = 9
y = 0
